### ISSUE TITLE
cycle 'add row' seems not to work fine

### ISSUE THREAD

**Issue by PierLuisVona** [midzer/urban-theme#2]
After several trying I'm not able to see 3 post in a row.
They're placing one by one.

![screen shot 2017-08-22 at 01 05 47](https://user-images.githubusercontent.com/16922970/29541715-2ebf7a74-86d6-11e7-8d63-db0e3dd3198b.png)

btw cycles in preview.html seems to be correct.
any idea why?

**Comment by midzer** [comment]
Hi @PierLuisVona 

after updating this theme and my local jekyll gem, i figured out it appears to be a regression within jekyll https://github.com/jekyll/jekyll/issues/6251

edit:
heh, i overlook that a quickfix has been posted there. i've pushed https://github.com/midzer/urban-theme/commit/df36d3d1eed85befa1458faab1ec7adf6afac218 to fix this issue. Thank you very much for reporting :+1: 

Have a nice day
midzer
