### ISSUE TITLE
How to include custom pictures 

### ISSUE THREAD

**Issue by nnamdei** [midzer/urban-theme#6]
kudos to a work well done. I would like to ask how to include custom photos to the front page as well as individual post page. I can see that you are using random pictures from a url. thanks.

**Comment by midzer** [comment]
hi @nnamdei 
In `_posts` folder you find several `.md` files. In those files variable `preview` has path of image of each entry (shown in main page).

For example you could replace it's value with something like `/assets/img/2015-10-18/preview.jpg` depending on where you have your preview image located.

Below those `---` there is the actual content of each post. You can put html or markdown syntax there.
Markdown syntax would be `![Picture 1](/assets/img/2015-10-18/bigImage.jpg)` for example.

Feel free to ask more questions if you like.
Have a nice day
midzer

**Comment by nnamdei** [comment]
thanks for the reply. I have a large collection of pictures and would like to categorize them and create a grid of these items on an individual post page just like the front page. how do I proceed with this.

**Comment by midzer** [comment]
Categorize those pictures via `tags` and each category/page contains specific images?
Sounds interesting and should be doable with jekyll.

I think you can use this theme as a good starter on this topic.
Have a look at Jekyll's front matter variables https://jekyllrb.com/docs/permalinks/#template-variables

**Comment by midzer** [comment]
I am going to close this for now. Feel free to post here if you still have issues on this topic
